'use client'

import { useState, useEffect } from 'react'
import useSWRInfinite from 'swr/infinite'
import fetcher from '@/lib/fetcher'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { Button } from '@/components/ui/button'
import { useRouter } from 'next/navigation'
import { timeAgo } from '@/lib/time-ago'
import {
  Wrench,
  ExternalLink,
  Search,
  X,
  ChevronDown,
  Loader2,
  CheckCircle2,
  XCircle,
  Clock,
} from 'lucide-react'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import EmptyState from '@/components/shared/empty-state'
import ErrorCard from '@/components/error/error-card'

type FixItem = {
  id: string
  repoName: string
  issueId: string
  issueTitle: string
  status: string
  prUrl: string | null
  branchName: string | null
  summary: string | null
  error: string | null
  createdAt: string
  updatedAt: string
}

type FixesData = {
  data: FixItem[]
  total: number
  totalPages: number
  page: number
  limit: number
}

const statusConfig: Record<string, { label: string; variant: 'default' | 'destructive' | 'secondary'; icon: typeof CheckCircle2 }> = {
  success: { label: 'Success', variant: 'default', icon: CheckCircle2 },
  failed: { label: 'Failed', variant: 'destructive', icon: XCircle },
  running: { label: 'Running', variant: 'secondary', icon: Clock },
}

const STATUS_OPTIONS = [
  { value: '', label: 'All statuses' },
  { value: 'success', label: 'Success' },
  { value: 'failed', label: 'Failed' },
  { value: 'running', label: 'Running' },
] as const

const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest first' },
  { value: 'oldest', label: 'Oldest first' },
] as const

function FixRow({ fix }: { fix: FixItem }) {
  const router = useRouter()
  const cfg = statusConfig[fix.status] ?? statusConfig.running
  const Icon = cfg.icon

  return (
    <div
      onClick={() => router.push(`/fixes/${fix.id}`)}
      className="flex items-center gap-3 px-4 py-3.5 cursor-pointer hover:bg-foreground/[0.02] transition-colors"
    >
      <Badge
        variant={cfg.variant}
        className="w-20 shrink-0 justify-center text-[10px] capitalize"
      >
        <Icon className="size-3 mr-1" />
        {cfg.label}
      </Badge>
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <p className="truncate text-sm font-medium">{fix.issueTitle}</p>
          {fix.prUrl && (
            <a
              href={fix.prUrl}
              target="_blank"
              rel="noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="shrink-0 text-muted-foreground hover:text-foreground"
            >
              <ExternalLink className="size-3" />
            </a>
          )}
        </div>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <span>{fix.repoName}</span>
          {fix.branchName && (
            <>
              <span aria-hidden="true">·</span>
              <span className="font-mono">{fix.branchName}</span>
            </>
          )}
        </div>
      </div>
      <span className="shrink-0 text-xs text-muted-foreground">
        {timeAgo(fix.createdAt)}
      </span>
    </div>
  )
}

export default function FixesPage() {
  const [searchInput, setSearchInput] = useState('')
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [sort, setSort] = useState<'newest' | 'oldest'>('newest')

  useEffect(() => {
    const timer = setTimeout(() => setSearch(searchInput), 300)
    return () => clearTimeout(timer)
  }, [searchInput])

  const getKey = (pageIndex: number, previousPageData: FixesData | null) => {
    if (previousPageData && !previousPageData.data.length) return null
    const params = new URLSearchParams({ page: String(pageIndex + 1), limit: '10' })
    if (search) params.set('search', search)
    if (status) params.set('status', status)
    if (sort !== 'newest') params.set('sort', sort)
    return `/api/fixes?${params.toString()}`
  }

  const { data, size, setSize, isValidating, isLoading, error } = useSWRInfinite<FixesData>(getKey, fetcher, {
    revalidateFirstPage: false,
  })

  const allItems = data ? data.flatMap((d) => d.data) : []
  const total = data?.[0]?.total ?? 0
  const totalPages = data?.[0]?.totalPages ?? 0
  const hasMore = size < totalPages

  if (error) {
    return <ErrorCard title="Unable to load fix history" />
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold">Fix History</h2>
        <p className="text-sm text-muted-foreground">
          All automated fixes generated by the mechanic agent across your repositories
        </p>
      </div>

      <section className="space-y-4">
        <div className="flex items-center gap-2">
          <div className="flex flex-1 items-center gap-2 rounded-md border bg-background px-3 text-sm h-9">
            <Search className="size-4 shrink-0 text-muted-foreground" />
            <input
              placeholder="Search fixes..."
              value={searchInput}
              onChange={(e) => setSearchInput(e.target.value)}
              className="w-full bg-transparent py-2 text-foreground placeholder-muted-foreground outline-none"
            />
            {searchInput && (
              <button
                onClick={() => setSearchInput('')}
                className="text-muted-foreground hover:text-foreground"
              >
                <X className="size-4" />
              </button>
            )}
          </div>

          <Select value={sort} onValueChange={(v) => setSort((v ?? 'newest') as 'newest' | 'oldest')}>
            <SelectTrigger className="w-[160px] !h-9">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {SORT_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select value={status} onValueChange={(v) => setStatus(v ?? '')}>
            <SelectTrigger className="w-[160px] !h-9">
              <SelectValue placeholder="All statuses" />
            </SelectTrigger>
            <SelectContent>
              {STATUS_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {isLoading ? (
          <div className="divide-y rounded-lg border">
            {[1, 2, 3].map((i) => (
              <div key={i} className="flex items-center gap-3 px-4 py-3.5">
                <Skeleton className="h-5 w-20 rounded-full" />
                <Skeleton className="h-4 flex-1" />
                <Skeleton className="h-3 w-20" />
              </div>
            ))}
          </div>
        ) : allItems.length === 0 ? (
          <EmptyState
            icon={Wrench}
            title={search || status ? 'No results' : 'No fixes yet'}
            description={
              search || status
                ? 'Try adjusting your search or filters.'
                : 'Fixes generated by the mechanic agent will appear here.'
            }
          />
        ) : (
          <>
            <p className="text-xs text-muted-foreground">
              Showing {allItems.length} of {total} fix{total !== 1 ? 'es' : ''}
            </p>
            <div className="divide-y rounded-lg border">
              {allItems.map((fix, i) => (
                <FixRow key={`${fix.id}-${i}`} fix={fix} />
              ))}
            </div>
            {hasMore && (
              <div className="flex justify-center">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSize(size + 1)}
                  disabled={isValidating}
                  className="gap-1 text-muted-foreground"
                >
                  {isValidating ? (
                    <Loader2 className="size-3 animate-spin" />
                  ) : (
                    <ChevronDown className="size-3" />
                  )}
                  View more
                </Button>
              </div>
            )}
          </>
        )}
      </section>
    </div>
  )
}
